# Generated by Django 4.0.5 on 2022-06-09 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0005_recipe_cook_time_recipe_main_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cook_time',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='main_ingredient',
        ),
    ]
