# Generated by Django 4.0.5 on 2022-06-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0006_remove_recipe_cook_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.CharField(choices=[('FIFTEEN', '15min'), ('THIRTY', '30min'), ('FOURTYFIVE', '45min'), ('ONE_HOUR', '1h')], default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='main_ingredient',
            field=models.CharField(choices=[('MEAT', 'MEAT'), ('FISH', 'Fish'), ('EGGS', 'Eggs'), ('VEGETABLES', 'Vegetables'), ('FRUIT', 'Fruit'), ('DAIRY', 'Dairy'), ('GRAIN', 'Grain'), ('TUBERS', 'Tubers'), ('LEGUMES', 'Legumes'), ('GRAIN', 'Grain')], default=None, max_length=20),
        ),
    ]
