# Generated by Django 4.0.5 on 2022-06-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0007_recipe_cook_time_recipe_main_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.CharField(choices=[('15min', 'FIFTEEN'), ('30min', 'THIRTY'), ('45min', 'FOURTYFIVE'), ('1h or more', 'ONE_HOUR_OR_MORE')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='main_ingredient',
            field=models.CharField(choices=[('meat', 'MEAT'), ('fish', 'FISH'), ('eggs', 'EGGS'), ('vegetables', 'VEGETABLES'), ('fruit', 'FRUIT'), ('dairy', ' DAIRY'), ('grain', 'GRAIN'), ('tubers', 'TUBERS'), ('legumes', 'LEGUMES')], default=None, max_length=20),
        ),
    ]
